config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root'homes#top'
    get'customers/edit'=>'customers#edit'
    get'customers/my_page'=>'customers#show'
    patch'customers/information'=>'customers#update'
    get'customers/unsubscribe'=>'customers#unsubscribe'
    patch'customers/withdraw'=>'customers#withdraw'
    resources :items, only: [:index, :show]
    delete'cart_items/destroy_all'=>'cart_items#clear'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get'orders/complete'=>'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    post'orders/confirm'=>'orders#confirm'
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]
    get'about'=>'homes#about'
    resources :registrations, only: [:new]
  end

  namespace :admin do
    root'homes#top'
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end
  # For detailson the DSL available within this file, see https://guides.rubyonrails.org/routing.html
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details
  has_many :cart_items
  has_one_attached :image

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
end

def add_tax_price
  (self.price * 1.10).round
end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def show
    @item= Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
     @item = Item.new(item_params)
     @item.save
     redirect_to admin_item_path(@item)
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    render :show
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h5>商品編集</h5>
<%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
  <h6>商品画像</h6>
  <%= f.file_field :image, accept: "image/*", class: "form-group" %>
  <h6>商品名</h6>
  <%= f.text_field :name, class: "form-group" %>
  <h6>商品説明</h6>
  <%= f.text_area :introduction, rows: 5, class: "form-group" %>
  <h6>税抜き価格</h6>
  <%= f.text_field :price, class: "form-group" %>円<br>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10">
<table class = "table table-hover">
<h5>商品一覧
<%= link_to new_admin_item_path do %>
  <i class="fa-solid fa-circle-plus fa-2x" ></i>
<% end %>
</h5>
<thead>
  <tr>
    <th>商品ID</th>
    <th></th>
    <th>商品名</th>
    <th></th>
    <th>税抜き価格</th>
  </tr>
</thead>
<tbody>
  <% @items.each do |item| %>
   <tr>
     <td><%= item.id %></td>
     <td></td>
     <td><%= link_to item.name, admin_item_path(item.id) %></td>
     <td></td>
     <td><%= item.price %></td>
   </tr>
  <% end %>
</tbody>
</table>
<%= paginate @items %>
  </div>
 </div>
</div>

app/views/admin/items/new.html.erb
<h5>商品新規登録</h5>
<%= form_with model: @item, url: admin_items_path do |f| %>
  <h6>商品画像</h6>
  <%= f.file_field :image, accept: "image/*", class: "form-group" %>
  <h6>商品名</h6>
  <%= f.text_field :name, class: "form-group" %>
  <h6>商品説明</h6>
  <%= f.text_area :introduction, rows: 5, class: "form-group" %>
  <h6>税抜き価格</h6>
  <%= f.text_field :price, class: "form-group" %>円<br>
  <%= f.submit "新規登録" %>
<% end %>

app/views/admin/items/show.html.erb
<h5>商品詳細</h5>
<div>
<%= image_tag @item.get_image(100,100) %>
<p>商品名<%= @item.name %></p>
<p>商品説明<%= @item.introduction %></p>
<p>税込価格<%= @item.add_tax_price %>円</p>
<p><%= link_to "編集する", edit_admin_item_path(@item.id) %></p>
</div>