config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root'homes#top'
    get'customers/edit'=>'customers#edit'
    get'customers/my_page'=>'customers#show'
    patch'customers/information'=>'customers#update'
    get'customers/unsubscribe'=>'customers#unsubscribe'
    patch'customers/withdraw'=>'customers#withdraw'
    resources :items, only: [:index, :show]
    delete'cart_items/destroy_all'=>'cart_items#clear'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get'orders/complete'=>'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    post'orders/confirm'=>'orders#confirm'
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]
    get'about'=>'homes#about'
    resources :registrations, only: [:new]
  end

  namespace :admin do
    root'homes#top'
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end
  # For detailson the DSL available within this file, see https://guides.rubyonrails.org/routing.html
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true

  def kana
    # kana属性の値を返すコードを記述する
  end

  def full_name
    last_name + " " + first_name
  end


  # def postal_code
  #   # 郵便番号を取得する処理を記述する
  # end

  # def address
  # end

  # def telephone_number
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer= Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

 private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h4>会員情報編集</h4>

<%= form_with model: @customer, url: admin_customer_path do |f| %>
<h5>会員ID</h5>
  <%= @customer.id %>
<h5>氏名</h5>
  <%= f.text_field :last_name, class: "form-group" %>
  <%= f.text_field :first_name, class: "form-group" %>
<h5>フリガナ</h5>
  <%= f.text_field :last_name_kana, class: "form-group" %>
  <%= f.text_field :first_name_kana, class: "form-group" %>
<h5>郵便番号</h5>
  <%= f.text_field :postal_code, class: "form-group" %>
<h5>住所</h5>
  <%= f.text_field :address, cols: 100, size: "50x", class: "form-group" %>
<h5>電話番号</h5>
  <%= f.text_field :telephone_number, class: "form-group" %>
<h5>メールアドレス</h5>
  <%= f.text_field :email, class: "form-group" %>
  <%= f.submit "変更を保存" %>
  <% end %>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10">
<table class = "table table-hover">
<h5>会員一覧</h5>
 <thead>
  <tr>
    <th>会員ID</th>
    <th></th>
    <th>氏名</th>
    <th></th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </tr>
 </thead>
<tbody>
  <% @customers.each do |customer| %>
   <tr>
     <td><%= customer.id %></td>
     <td></td>
     <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
     <td></td>
     <td><%= customer.email %></td>
     <td>
      <% if customer.is_active %>
       有効
      <% else %>
       退会
      <% end %>
     </td>
   </tr>
  <% end %>
</tbody>
</table>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="card">

  <div class="card-body">

    <p class="card-text"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</p>

    <p class="card-text"><strong>会員ID</strong><%= @customer.id %></p>

    <p class="card-text"><strong>氏名</strong><%= @customer.last_name %><%= @customer.first_name %></p>

    <p class="card-text"><strong>カナ</strong><%= @customer.last_name_kana %><%= @customer.first_name_kana %></p>

    <p class="card-text"><strong>郵便番号</strong><%= @customer.postal_code %></p>

    <p class="card-text"><strong>住所</strong><%= @customer.address %></p>

    <p class="card-text"><strong>電話番号</strong><%= @customer.telephone_number %></p>

    <p class="card-text"><strong>メールアドレス</strong><%= @customer.email %></p>

    <p class="card-text"><strong>会員ステータス</strong><% if @customer.is_active %>
       有効
      <% else %>
       退会
      <% end %></p>
  </div>
</div>
  <%= link_to edit_admin_customer_path(@customer), class:"button" do %>
  編集する
  <% end %>
  <%= link_to admin_root_path, class:"button" do %>
  注文履歴一覧を見る
  <% end %>