config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root'homes#top'
    get'customers/edit'=>'customers#edit'
    get'customers/my_page'=>'customers#show'
    patch'customers/information'=>'customers#update'
    get'customers/unsubscribe'=>'customers#unsubscribe'
    patch'customers/withdraw'=>'customers#withdraw'
    resources :items, only: [:index, :show]
    delete'cart_items/destroy_all'=>'cart_items#clear'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get'orders/complete'=>'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    post'orders/confirm'=>'orders#confirm'
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]
    get'about'=>'homes#about'
    resources :registrations, only: [:new]
  end

  namespace :admin do
    root'homes#top'
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end
  # For detailson the DSL available within this file, see https://guides.rubyonrails.org/routing.html
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  def item_amount
    total = 0
    self.order_details.each do |order_detail|
      total += order_detail.quantity
    end
    return total
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order_details = OrderDetail.where(order_id: params[:id])
    @order = Order.find(params[:id])
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h4>注文履歴詳細</h4>

<%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
  <table>
    <tr>
      <td>購入者</td>
      <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <td>配送先</td>
      <td><%= @order.postal_code%><%= @order.address %><%= @order.name %></td>
    </tr>
    <tr>
      <td>支払い方法</td>
      <td><%= @order.payment_method_i18n%></td>
    </tr>
  </table>
<% end %>

<table>
  <tr>
    <td>商品名</td>
    <td>単価(税込)</td>
    <td>数量</td>
    <td>小計</td>
  </tr>
  <% @sum = 0 %>
<% @order_details.each do |order_detail| %>
<% @sum += order_detail.item.add_tax_price %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.add_tax_price %></td>
          <td><%= order_detail.quantity %></td>
          <td><%= order_detail.item.add_tax_price * order_detail.quantity %></td>
        </tr>
<% end %>
      <tr>
        <td>商品合計</td>
        <td><%= @sum %>円</td>
      </tr>
      <tr>
        <td>送料</td>
        <td>800円</td>
      </tr>
      <tr>
        <td>請求金額合計</td>
        <td><%= @sum + 800 %>円</td>
      </tr>
  </table>