config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root'homes#top'
    get'customers/edit'=>'customers#edit'
    get'customers/my_page'=>'customers#show'
    patch'customers/information'=>'customers#update'
    get'customers/unsubscribe'=>'customers#unsubscribe'
    patch'customers/withdraw'=>'customers#withdraw'
    resources :items, only: [:index, :show]
    delete'cart_items/destroy_all'=>'cart_items#clear'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get'orders/complete'=>'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    post'orders/confirm'=>'orders#confirm'
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]
    get'about'=>'homes#about'
    resources :registrations, only: [:new]
  end

  namespace :admin do
    root'homes#top'
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end
  # For detailson the DSL available within this file, see https://guides.rubyonrails.org/routing.html
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    "〒" + postal_code + address + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :customer
belongs_to :item

def subtotal
  item.add_tax_price * amount
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true

  def kana
    # kana属性の値を返すコードを記述する
  end

  def full_name
    last_name + " " + first_name
  end


  # def postal_code
  #   # 郵便番号を取得する処理を記述する
  # end

  # def address
  # end

  # def telephone_number
  # end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details
  has_many :cart_items
  has_one_attached :image

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
end

def add_tax_price
  (self.price * 1.10).round
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  def item_amount
    total = 0
    self.order_details.each do |order_detail|
      total += order_detail.quantity
    end
    return total
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer= Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

 private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all.page(params[:page]).per(10)
    
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def show
    @item= Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
     @item = Item.new(item_params)
     @item.save
     redirect_to admin_item_path(@item)
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    render :show
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order_details = OrderDetail.where(order_id: params[:id])
    @order = Order.find(params[:id])
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ca5a5ebfe0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
      <ul>
        <% if customer_signed_in? %>
         <li>
          <%= link_to "マイページ", customers_my_page_path %>
         </li>
         <li>
          <%= link_to "商品一覧", items_path %>
         </li>
         <li>
          <%= link_to "カート", cart_items_path %>
         </li>
         <li>
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
         </li>
        <% elsif admin_signed_in? %>
         <li>
          <%= link_to "商品一覧", admin_items_path %>
         </li>
         <li>
          <%= link_to "会員一覧", admin_customers_path %>
         </li>
         <li>
          <%= link_to "注文履歴一覧", admin_root_path %>
         </li>
         <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        </li>
        <% else %>
         <li>
          <%= link_to "LOGO", root_path %>
         </li>
         <li>
          <%= link_to "About", about_path %>
         </li>
         <li>
          <%= link_to "商品一覧", items_path %>
         </li>
         <li>
          <%= link_to "新規登録", new_customer_registration_path %>
         </li>
         <li>
          <%= link_to "ログイン", new_customer_session_path %>
         </li>
        <% end %>
      </ul>
</header>

    <%= yield %>
  </body>
</html>